name: sdmx.org learning catalogue entry
description: Add an entry to the sdmx.org catalogue of learning resources
title: (e.g. New elearning on SDMX data modelling)
labels: ["changerequest"]
body:
  - type: markdown
    attributes:
      value: |
        **Please complete the following details describing your SDMX learning resource. You will need to provide two URLs**
        - URL of a web page for the learning resource, for instance detailing the curriculum and how to enroll
        - URL of an image for the learning resource that will appear in the sdmx.org learning catalogue
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g. email@example.com
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Course title
      description: The title of the course or learning resource
      placeholder: e.g. Introduction to SDMX data modelling for statisticians 
    validations:
      required: true      
  - type: checkboxes
    id: topic
    attributes:
      label: Topic
      description: Select one or two topics
      options:
        - label: SDMX data modelling
        - label: Labour statistics
        - label: European National Accounts
        - label: SDGs
        - label: SDMX tools
        - label: .Stat Suite
        - label: Fusion Metadata Registry
        - label: SDMX Matrix Generator
        - label: SDMX Converter
        - label: Euro SDMX Registry   
        - label: Other - suggest a new topic
  - type: input
    id: newtopics
    attributes:
      label: Suggest a new topic if needed
      description: Suggest a new topic if none of the above propely describe your course
    validations:
      required: false   
  - type: dropdown
    id: type
    attributes:
      label: Course type
      description: Select the type of course
      options:
        - elearning, self-paced
        - In-person, instructor led
        - Online, instructor led
        - Webinar, recording
        - Webinar, live
      default: 0
    validations:
      required: true    
  - type: input
    id: price
    attributes:
      label: Course price
      description: The price for a student to enroll in your course
      value: Free
    validations:
      required: true         
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A short summary of the course or learning resource - 50 words or less
    validations:
      required: true
  - type: dropdown
    id: sponsor
    attributes:
      label: Sponsor
      description: Select who is providing the course
      options:
        - Other - suggest a new sponsor below
        - ADB
        - BIS
        - Eurostat
        - ILO
        - SIS-CC (OECD)
        - UNSD
      default: 0
    validations:
      required: true
  - type: input
    id: newsponsor
    attributes:
      label: Suggest a new sponsor if needed
      description: Suggest a new sponsor here is you selected 'Other' above
    validations:
      required: false           
  - type: input
    id: courseurl
    attributes:
      label: The URL of your course
      description: Please enter a publicly-accessible URL of a web page where prospective students can find out more about your course and enroll 
    validations:
      required: true   
  - type: input
    id: imageurl
    attributes:
      label: The URL of an image for your course
      description: Please enter a publicly-accessible URL of an image for your course in the sdmx.org learning catalogue
    validations:
      required: true
